Repository sw20-tug/ASD-Morning-6, pull requests merged in 2020-04, with the labels that each got.

#29 COOK_012 (#26) added Tests for RecipeManager and refactored code
  .gitignore
  ASD-Morning-6.iml
  src/app/controllers/AddRecipeController.java
  src/app/models/Recipe.java
  src/app/models/RecipeManager.java
  src/test/ControllerTest.java
  src/test/RecipeManagerTest.java
Labels: enhancement

#31 Introduce new README :sparkles:
  README.md
Labels: documentation

#42 COOK_013 folder config hotfix [DL,KL]
  appdata/images/recipeimages/dummy.png
Labels: bug
